analysis: "coordinate"
verbose: False
debug: False
graph: False
pdbfile: "pentapeptide/init-ww-penta.pdb"
dcdfiles:
  - "pentapeptide/job1-protein.dcd"
  - "pentapeptide/job2-protein.dcd"
pname: "pentapeptide"
startRes: 1
endRes: 5
icaDim: 8
sliceVal: 1
saveDir: "savefiles/"
logfile: "log/log.txt"
figDir: "savefiles/figures/"
