name: Coverage
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.3.0
        with:
          python-version: "3.9"
          architecture: x64
      - run: pip install nox==2020.12.31
      - run: pip install poetry==1.1.5
      - run: pip install nox-poetry==0.8.4
      - run: nox --sessions tests-3.9 coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
